### PR TITLE
Final TypeScript changes

### LINKED ISSUE #336: Final TypeScript Changes
## Summary
This issue tracks a few final TypeScript changes that require fixing before the TypeScript beta can be released.

## Scope
- [x] `assignGroupID` method requires a better return type
- [x] Incorrect default generic types for the `JSONRequest` abstract class 
- [x] `Account` type should be exported
- [x] Specify `SuggestedParams` type for the suggested parameters client request
- [x] Improve `makeKeyRegistrationTxn(...)` type definitions using overloads
- [x] Warn if trying to create a client with a base server of `localhost`, since `localhost` is not considered a valid URL

## Urgency
Requires for TypeScript beta release.

### PR DESCRIPTION
**Pull request by jdtzmn**
* Remove deprecated ESLint setting

* Specify `SuggestedParams` type for the SuggestedParams client request

* Fix default generic types of the `JSONRequest` class

* Provide better return type for the `assignGroupID` method

* Export `Account` type

Closes #336.

### CODE REVIEW

File: src/makeTxn.ts [hunk 1]
```diff
@@ -262,9 +323,24 @@ export function makeKeyRegistrationTxnWithSuggestedParamsFromObject(
...
+export function makeKeyRegistrationTxnWithSuggestedParamsFromObject(
+  o: Pick<
+    RenameProperty<
+      MustHaveSuggestedParams<KeyRegistrationTxn>,
+      'reKeyTo',
+      'rekeyTo'
+    >,
+    'from' | 'note' | 'suggestedParams' | 'rekeyTo'
+  > & {
+    nonParticipation?: true;
```
Comment (jasonpaulos) [inline src/makeTxn.ts:339]:
```suggestion
    nonParticipation: true;
```
I am seeing the following code pass incorrectly, but I believe this change should fix it:
```javascript
algosdk.makeKeyRegistrationTxnWithSuggestedParamsFromObject({
    from: account.addr,
    // none of the key params or nonParticipation
    suggestedParams: await client.getTransactionParams().do(),
})
```

**Review by jasonpaulos — APPROVED** [review]
Pending tests, looks great!
