### PR TITLE
Fix encoding of all 0 lease and assetMetadataHash

### LINKED ISSUE #272: Make sure the SDK and algod agree on encoding
## Summary
If the `lease` or `assetMetadataHash` fields of `Transaction` are encoded in a way inconsistant with algod, signatures generated by this SDK will appear to be invalid to algod.

## Scope
Make sure that the SDK correctly validates and omits (when empty) the `lease` and `assetMetadataHash` fields.

## Urgency
This is a small but important fix.

### PR DESCRIPTION
**Pull request by jasonpaulos**
This PR fixes an encoding inconsistency between this SDK and algod when `lease` or `assetMetadataHash` consist of all zeros. A similar fix for the Python SDK was recently merged: algorand/py-algorand-sdk#174.

Fixes #272.

### CODE REVIEW

File: src/transaction.js [hunk 1]
```diff
@@ -101,13 +101,17 @@ class Transaction {
...
                 throw Error("assetMetadataHash must be a " + ASSET_METADATA_HASH_LENGTH + " byte Uint8Array or string.");
+            }
+
+            if (assetMetadataHash.every(value => value === 0)) {
+                // if hash contains all 0s, omit it
+                assetMetadataHash = undefined;
+            }
         } else {
             assetMetadataHash = undefined;
         }
```
Comment (algorotem) [inline src/transaction.js:117]: Since the code conditioning on the value of `assetMetadaataHash`, consider having as a sequence of if statements and avoid the `else`s

**Review by algorotem — CHANGES_REQUESTED** [review]

File: src/transaction.js (hunk 1 above)
Comment (jasonpaulos) [reply src/transaction.js:117]: I think this section of code already has the minimum number of `else`s.

**Review by jdtzmn — APPROVED** [review]
Looks good!
