### PR TITLE
fix: remove cross-fetch

### LINKED ISSUE #823: Failed to execute 'fetch' on 'Window': Illegal invocation
### Subject of the issue

Since algosdk v2.5.0 a [sample svelte project](https://github.com/nullun/vite-svelte-algorand) I have now breaks when built and served from a web server, giving the following error message in the console when the page loads.
`Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation`

A little digging reveals that it is https://github.com/algorand/js-algorand-sdk/pull/794 which causes the issue, and so I believe it's to do with cross-fetch being polyfilled?

The code works if I run `npm run dev` locally in a development environment, it's only broken when I do `npm run build` and serve the dist folder from a web server. The project is currently [deployed](https://vite-svelte-algorand.netlify.app/) using v2.4.0 and it's working as expected, but I'm unable to update to 2.5.0 due to the cross-fetch update.

### Your environment

macOS 13.5.1
node v20.5.1
npm 9.8.0

### Steps to reproduce

1. `git clone git@github.com:nullun/vite-svelte-algorand.git`
2. `cd vite-svelte-algorand`
3. `npm install`
4. `npm run build`
5. Host the `dist` folder on a webserver, I use apache2 locally and have `~/Sites` set to `127.0.0.1/~nullun/`. So I would do something like `ln -s ~/vite-svelte-algorand/dist ~/Sites/dist`
6. Visit http://127.0.0.1/~nullun/dist/ or whatever your destination is

### Expected behaviour

The page loads without errors, showing the latest Algorand Mainnet round.

### Actual behaviour

Page loads with an error, preventing retrieval of latest Algorand Mainnet round.

### PR DESCRIPTION
**Pull request by PhearZero**
# ℹ️ Overview

With the End of Life of Node 16 and engine set to `>=18`, we can safely use native `fetch`.

Consumers targeting `ie11` or other engines can handle the [fetch pollyfill](https://www.npmjs.com/package/whatwg-fetch).  

## 📝 Issues

Fixes #823 
Relates to #831

### CODE REVIEW

File: tests/cucumber/steps/index.js [hunk 1]
```diff
@@ -54,6 +54,7 @@ if (browser) {
   } else if (browser === 'chrome') {
     require('chromedriver');
     browserHeaders = [
+      'accept-language',
```
Comment (jasonpaulos) [inline tests/cucumber/steps/index.js:57]: In CI this test is failing for chrome because `accept-language` isn't present. Did this behavior differently for you locally?

Comment (PhearZero) [reply tests/cucumber/steps/index.js:57]: `TEST_BROWSER=chrome make unit` is passing locally for Ubuntu 20.04.3 LTS using `v18.17.1` and `v20.5.0`

Comment (jasonpaulos) [reply tests/cucumber/steps/index.js:57]: Got it. I believe this test is too brittle for reliable use. Could you remove the `@unit.client-no-headers` line from `unit.tags` in this PR?

I will create a separate issue to fix the test (it likely should be checking that certain headers aren't present, not that all present headers must match a hardcoded list).

**Comment by nullun** [comment]
Just want to confirm that this PR fixes #823 and I'll close my revert (#831).

**Comment by PhearZero** [comment]
> Just want to confirm that this PR fixes #823 and I'll close my revert (#831).

@nullun Just deployed an example with the following dependency in `package.json`:

```json
{
  "algosdk": "github:PhearZero/js-algorand-sdk#fix/cross-fetch"
}
```

And the current render of `getTransactionParams` : https://wrangler-test.phearzero.workers.dev/

**Review by jasonpaulos — APPROVED** [review]
Great work, happy to remove this dependency
