### PR TITLE
Use node’s `url` module for URL construction in the HTTPClient constructor

### LINKED ISSUE #261: Port in algod/indexer does not work with URL starting with some path
The port is concatenated to the baseserver URL on https://github.com/algorand/js-algorand-sdk/blob/develop/src/client/client.js#L41.

This means that it does not work properly when baseserver contains some path beyond just the server.

Concretely, to use algoexplorer.io indexer, you need to write
```js
const algodIndexer = new algosdk.Indexer("", "https://api.testnet.algoexplorer.io/idx2", "");
```
but not:
```js
const algodIndexer = new algosdk.Indexer("", "https://api.testnet.algoexplorer.io/idx2", 443);
```
nor:
```js
const algodIndexer = new algosdk.Indexer("", "https://api.testnet.algoexplorer.io/idx2");
```

Maybe the best solution is to add a comment in the documentation of the constructor of the indexer and algod clients.

### PR DESCRIPTION
**Pull request by jdtzmn**
Fixes #261.

### CODE REVIEW

File: src/client/client.ts [hunk 1]
```diff
@@ -120,16 +122,28 @@ export default class HTTPClient {
...
+    const address = new Url(
+      path.posix.join(this.baseURL.pathname, relativePath),
+      this.baseURL
+    );
+    return address.toString();
+  }
+
   /**
    * Send a GET request.
    * @param {string} path The path of the request.
```
Comment (jasonpaulos) [inline src/client/client.ts:149]:
```suggestion
   * @param {string} relativePath The path of the request.
```

**Review by jasonpaulos — APPROVED** [review]
Jus one small docs nit, feel free to merge after fixing.
